apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sample-secrets
  namespace: default

# 管理する秘匿情報に応じて設定する
# 種類一覧：https://kubernetes.io/ja/docs/concepts/configuration/secret/#secret-types
type: Qpaque

# dataフィールドはbase64で暗号化した値を記載する
data:
  pass1: 'c2FtcGxlUGFzc3dvcmQxCg=='

# stringDataフィールドは値を直接記載する
stringData:
  pass2: 'samplePassword2'
