apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sample-secrets
  namespace: default

# 管理する秘匿情報に応じて設定する
# 種類一覧：https://kubernetes.io/ja/docs/concepts/configuration/secret/#secret-types
type: Qpaque

# dataフィールドはbase64で暗号化した値を記載する
data:
  pass1: 'c2FtcGxlUGFzc3dvcmQxCg=='

# stringDataフィールドは値を直接記載する
stringData:
  pass2: 'samplePassword2'

---

# Secretをpodの環境変数に設定する
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    env:
      # k環境変数名
      - name: PASSWORD1
        # env.valueFrom.SecretKeyRefにSecretの情報を記述する
        valueFrom:
          secretKeyRef:
            # Secretのnameを指定
            name: sample-secrets
            # Secretのdata名を指定
            key: pass1
      - name: PASSWORD2
        valueFrom:
          secretKeyRef:
            name: sample-secrets
            key: pass2
  restartPolicy: Never
