# Secretをpodの環境変数に設定する
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    env:
      # k環境変数名
      - name: PASSWORD1
        # env.valueFrom.SecretKeyRefにSecretの情報を記述する
        valueFrom:
          secretKeyRef:
            # Secretのnameを指定
            name: sample-secrets
            # Secretのdata名を指定
            key: pass1
      - name: PASSWORD2
        valueFrom:
          secretKeyRef:
            name: sample-secrets
            key: pass2
  restartPolicy: Never
